// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr4oI7vZvJ08uPaLaZ9tvl0Op33ZTbylU',
    appId: '1:923862953721:web:17fedd68fc41cdcfa3fc28',
    messagingSenderId: '923862953721',
    projectId: 'pixandrix-a51e4',
    authDomain: 'pixandrix-a51e4.firebaseapp.com',
    storageBucket: 'pixandrix-a51e4.appspot.com',
    measurementId: 'G-H2YX831H53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtxQM3Nsop1fd4lMD9Ub0nigX6Am4BzEY',
    appId: '1:923862953721:android:44afca0fb8d74c60a3fc28',
    messagingSenderId: '923862953721',
    projectId: 'pixandrix-a51e4',
    storageBucket: 'pixandrix-a51e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7WqNu_0k1pAPipnlxZUFzey1416x9o0I',
    appId: '1:923862953721:ios:ad9c104a0c5748e7a3fc28',
    messagingSenderId: '923862953721',
    projectId: 'pixandrix-a51e4',
    storageBucket: 'pixandrix-a51e4.appspot.com',
    iosBundleId: 'com.example.pixandrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7WqNu_0k1pAPipnlxZUFzey1416x9o0I',
    appId: '1:923862953721:ios:ad9c104a0c5748e7a3fc28',
    messagingSenderId: '923862953721',
    projectId: 'pixandrix-a51e4',
    storageBucket: 'pixandrix-a51e4.appspot.com',
    iosBundleId: 'com.example.pixandrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr4oI7vZvJ08uPaLaZ9tvl0Op33ZTbylU',
    appId: '1:923862953721:web:fbcff117c263eb36a3fc28',
    messagingSenderId: '923862953721',
    projectId: 'pixandrix-a51e4',
    authDomain: 'pixandrix-a51e4.firebaseapp.com',
    storageBucket: 'pixandrix-a51e4.appspot.com',
    measurementId: 'G-J1EF6J4TEK',
  );
}
